// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Shared token definitions for nanosiem query language
 * Used by both syntax-highlight.ts (search) and detection-language.ts (CodeMirror)
 *
 * IMPORTANT: This is the single source of truth for query language tokens.
 * Update this file to add new keywords, functions, or operators.
 */

// Query keywords (boolean operators and comparison keywords)
export const QUERY_KEYWORDS = [
  'AND', 'OR', 'NOT', 'IN', 'CONTAINS', 'LIKE', 'STARTSWITH', 'ENDSWITH', 'INTERVAL',
] as const;

// Pipe commands
export const PIPE_COMMANDS = [
  'stats', 'streamstats', 'eventstats', 'where', 'search', 'by', 'count', 'distinct_count', 'dc', 'sum', 'avg', 'min', 'max',
  'values', 'list', 'first', 'last', 'table', 'sort', 'head', 'tail', 'timechart', 'lookup',
  'inputlookup', 'eval', 'dedup', 'uniq', 'output', 'prevalence', 'rex', 'extract', 'regex', 'fields', 'rename', 'top', 'rare',
  'transaction', 'fillnull', 'mvexpand', 'spath', 'append', 'join', 'bin', 'bucket', 'risk', 'sample',
  'reverse', 'anomaly', 'funnel', 'sequence', 'chart', 'format', 'return', 'tree', 'resolve_identity',
  'asset', 'cloud', 'lateral', 'ai', 'baseline',
] as const;

// Command parameters
export const COMMAND_PARAMS = [
  'enrich', 'window', 'current', 'span', 'limit', 'as', 'field', 'mode', 'score', 'entity',
  'factor', 'weight', 'startswith', 'endswith', 'maxspan', 'maxevents', 'keeplast',
  'case_insensitive', 'threshold', 'method', 'hop', 'parent', 'child', 'label', 'detail',
  'prevalence', 'process', 'web', 'root', 'max_age', 'sections', 'show_mfa',
  'principal', 'account', 'provider',
  'prompt', 'max_rows', 'seed', 'maxhops', 'methods',
  'url', 'format', 'key', 'timeout', 'cache_ttl', 'value', 'type', 'sliding',
  'dims',  // baseline command — comma-separated dimension filter
] as const;

// Eval functions (string, math, date, IP, encoding, etc.)
export const EVAL_FUNCTIONS = [
  // String functions
  'len', 'substr', 'upper', 'lower', 'trim', 'ltrim', 'rtrim', 'split', 'replace', 'concat',
  'printf', 'format',
  // Math functions
  'round', 'ceil', 'floor', 'abs', 'pow', 'sqrt', 'log', 'ln', 'log10', 'min', 'max',
  // Conditional functions
  'if', 'case', 'coalesce', 'null', 'nullif', 'isnull', 'isnotnull', 'typeof',
  // Type conversion
  'tonumber', 'tostring', 'toint', 'toNumber', 'toString',
  // Date/time functions
  'now', 'relative_time', 'strftime', 'strptime', 'epoch', 'from_epoch', 'date_add', 'date_sub',
  'date_diff', 'date_trunc', 'date_part', 'year', 'month', 'day', 'hour', 'minute', 'second',
  'dayofweek', 'week', 'quarter', 'timezone', 'to_timestamp', 'to_date', 'today', 'yesterday',
  // Multivalue functions
  'mvcount', 'mvindex', 'mvfilter', 'mvjoin', 'mvsort', 'mvdedup',
  // IP/Network functions
  'cidrmatch', 'cidr_match', 'is_private_ip', 'is_public_ip', 'is_loopback',
  'ipv4_to_int', 'int_to_ipv4',
  // Domain/URL functions
  'extract_domain', 'extract_tld', 'extract_path', 'extract_root_domain', 'extract_subdomain',
  'domain_depth', 'defang', 'refang',
  // Encoding functions
  'base64_encode', 'base64_decode', 'hex_encode', 'hex_decode', 'url_encode', 'url_decode',
  'urldecode',
  // Hashing functions
  'md5', 'sha1', 'sha256', 'sha512',
  // String matching
  'like', 'match', 'exact', 'searchmatch',
  // Security/analysis functions
  'entropy', 'levenshtein', 'ngram_distance',
  // Regex functions
  'regex_extract', 'regex_replace',
  // Array functions
  'array_length', 'array_join', 'array_contains', 'reverse',
] as const;

// Boolean and enum values (true/false, sort orders, join types, anomaly methods, window types, interval units)
export const BOOLEAN_VALUES = [
  'true', 'false',
  'asc', 'desc',           // Sort order
  'inner', 'left', 'outer', // Join types
  'zscore', 'mad',          // Anomaly detection methods
  'sliding', 'tumbling',    // Window types
  // Interval units (for INTERVAL N UNIT syntax)
  'microsecond', 'microseconds', 'millisecond', 'milliseconds',
  'second', 'seconds', 'minute', 'minutes', 'hour', 'hours',
  'day', 'days', 'week', 'weeks', 'month', 'months', 'year', 'years',
] as const;

// Enriched fields (geo/ASN enrichment)
export const ENRICHED_FIELDS = [
  'enriched_src_country', 'enriched_src_country_code', 'enriched_src_continent',
  'enriched_src_asn', 'enriched_src_as_name',
  'enriched_dest_country', 'enriched_dest_country_code', 'enriched_dest_continent',
  'enriched_dest_asn', 'enriched_dest_as_name',
] as const;

// IOC (threat intelligence) fields
export const IOC_FIELDS = [
  'ioc_matched', 'ioc_confidence',
  'ioc_src_ip_threat_type', 'ioc_src_ip_malware', 'ioc_src_ip_confidence',
  'ioc_dest_ip_threat_type', 'ioc_dest_ip_malware', 'ioc_dest_ip_confidence',
  'ioc_domain_threat_type', 'ioc_domain_malware', 'ioc_domain_confidence',
  'ioc_hash_threat_type', 'ioc_hash_malware', 'ioc_hash_confidence',
] as const;

// Computed fields generated by pipe commands (anomaly, prevalence, risk, ai, etc.)
export const COMPUTED_FIELDS = [
  // ai command
  'ai_verdict', 'ai_confidence', 'ai_reasoning',
  // anomaly command
  'anomaly_score', 'is_anomaly',
  // prevalence command
  'prevalence_score', 'prevalence_first_seen', 'prevalence_last_seen',
  'total_occurrences', 'prevalence_type', 'prevalence_artifact', 'host_count', 'is_rare',
  // risk command
  'risk_score', 'risk_factors', 'risk_level',
  // transaction command
  'eventcount', 'duration', 'transaction_start', 'transaction_end',
  // sequence command
  'sequence_duration_seconds', 'sequence_duration', 'sequence_count',
  // top/rare command
  'count', 'percent',
] as const;

// Field aliases — common analyst muscle-memory names that map to UDM fields.
export const FIELD_ALIASES = [
  'sourcetype',    // → source_type
  'host',          // → src_host / dest_host
] as const;

// Tree command step parameters (step1, step2, etc.) - regex pattern
export const TREE_STEP_PATTERN = /^step\d+$/i;

// Pre-built Sets for efficient lookup (typed as Set<string> for flexible .has() calls)
export const QUERY_KEYWORDS_SET: Set<string> = new Set(QUERY_KEYWORDS.map(k => k.toLowerCase()));
export const PIPE_COMMANDS_SET: Set<string> = new Set(PIPE_COMMANDS);
export const COMMAND_PARAMS_SET: Set<string> = new Set(COMMAND_PARAMS);
export const EVAL_FUNCTIONS_SET: Set<string> = new Set(EVAL_FUNCTIONS);
export const BOOLEAN_VALUES_SET: Set<string> = new Set(BOOLEAN_VALUES.map(v => v.toLowerCase()));
export const ENRICHED_FIELDS_SET: Set<string> = new Set(ENRICHED_FIELDS);
export const IOC_FIELDS_SET: Set<string> = new Set(IOC_FIELDS);
export const COMPUTED_FIELDS_SET: Set<string> = new Set(COMPUTED_FIELDS);
export const FIELD_ALIASES_SET: Set<string> = new Set(FIELD_ALIASES);

// Pre-built regex patterns for tokenizers
export const QUERY_KEYWORDS_PATTERN = new RegExp(
  `^(${QUERY_KEYWORDS.join('|')})\\b`, 'i'
);

export const PIPE_COMMANDS_PATTERN = new RegExp(
  `^(${PIPE_COMMANDS.join('|')})\\b`, 'i'
);

export const COMMAND_PARAMS_PATTERN = new RegExp(
  `^(${COMMAND_PARAMS.join('|')}|step\\d+)\\b`, 'i'
);

export const EVAL_FUNCTIONS_PATTERN = new RegExp(
  `^(${EVAL_FUNCTIONS.join('|')})\\b`, 'i'
);

export const BOOLEAN_VALUES_PATTERN = new RegExp(
  `^(${BOOLEAN_VALUES.join('|')})\\b`, 'i'
);
