// SPDX-License-Identifier: AGPL-3.0-or-later

//! SIEM Health Check API handlers
//!
//! Provides endpoints for listing, retrieving, and triggering SIEM health check reports.
//! Reports are AI-driven analyses of ingestion, parsing, and detection quality.

use std::collections::BTreeSet;

use axum::{
    Extension, Json,
    extract::{Path, Query, State},
};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::error::ApiError;
use crate::middleware::AuthContext;
use crate::state::AppState;
use nanosiem_core::siem_health::{SiemHealthReport, SiemHealthReportSummary, SiemHealthRepository};

/// NAN-1801: post-fetch source-scope filter for precomputed health reports.
///
/// Health reports are generated by a SYSTEM scheduler with an unrestricted
/// view of the fleet, so per-source telemetry cannot be scoped with a live
/// WHERE at read time — instead the per-source vectors inside the stored
/// `metrics` JSON blob are filtered against the viewer's effective deny set
/// (per-source RBAC ∪ the `audit` gate) before the report leaves the API.
///
/// Filtered paths (every `source_type`-keyed vector in `CollectedMetrics`):
/// - `ingestion.source_volumes`      (`SourceVolumeMetric.source_type`)
/// - `ingestion.silent_sources`      (bare `Vec<String>` of source types)
/// - `parsing.field_coverage`        (`FieldCoverageMetric.source_type`)
/// - `parsing.high_ext_sources`      (`ExtUsageMetric.source_type`)
/// - `enrichment.per_source_coverage` (`EnrichmentCoverageMetric.source_type`)
///
/// Cluster-wide/global fields (totals, insert-integrity probes, per-column
/// lowercase violations, rule/alert stats, scores) have no `source_type`
/// dimension and are deliberately left untouched.
///
/// An EMPTY deny set returns immediately — the report stays byte-identical
/// for unrestricted viewers. Comparison is lowercase-on-both-sides, mirroring
/// the F1 SQL predicate builder. Entries whose `source_type` cannot be read
/// as a string are dropped (fail-closed) rather than leaked.
fn filter_report_for_viewer(report: &mut SiemHealthReport, deny: &BTreeSet<String>) {
    if deny.is_empty() {
        return;
    }
    let deny_lower: BTreeSet<String> = deny.iter().map(|s| s.to_lowercase()).collect();

    // Object arrays keyed by a `source_type` string field.
    for (section, field) in [
        ("ingestion", "source_volumes"),
        ("parsing", "field_coverage"),
        ("parsing", "high_ext_sources"),
        ("enrichment", "per_source_coverage"),
    ] {
        if let Some(entries) = report
            .metrics
            .get_mut(section)
            .and_then(|s| s.get_mut(field))
            .and_then(|f| f.as_array_mut())
        {
            entries.retain(|entry| {
                entry
                    .get("source_type")
                    .and_then(|v| v.as_str())
                    .is_some_and(|st| !deny_lower.contains(&st.to_lowercase()))
            });
        }
    }

    // `silent_sources` is a bare array of source-type strings.
    if let Some(entries) = report
        .metrics
        .get_mut("ingestion")
        .and_then(|s| s.get_mut("silent_sources"))
        .and_then(|f| f.as_array_mut())
    {
        entries.retain(|v| {
            v.as_str()
                .is_some_and(|st| !deny_lower.contains(&st.to_lowercase()))
        });
    }
}

/// Query parameters for listing health reports
#[derive(Debug, Deserialize, utoipa::IntoParams)]
pub struct ListReportsParams {
    /// Maximum number of reports to return (default: 20, max: 100)
    #[serde(default = "default_limit")]
    pub limit: i64,
    /// Offset for pagination (default: 0)
    #[serde(default)]
    pub offset: i64,
}

fn default_limit() -> i64 {
    20
}

/// Paginated list of health report summaries
#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct ListReportsResponse {
    pub reports: Vec<SiemHealthReportSummary>,
    pub total: i64,
    pub limit: i64,
    pub offset: i64,
}

/// Response from triggering a health check
#[derive(Debug, Serialize, utoipa::ToSchema)]
pub struct TriggerResponse {
    /// The ID of the newly created report, if successful
    pub report_id: Option<Uuid>,
    /// Human-readable status message
    pub message: String,
}

/// List SIEM health report summaries (paginated)
///
/// Returns a paginated list of health report summaries, ordered by most recent first.
/// Summaries omit the full metrics and dimension details for efficiency.
///
/// Requires the `settings:system` permission (NAN-1801 — health reports carry
/// fleet-wide per-source telemetry).
///
/// GET /api/siem-health/reports
#[utoipa::path(
    get,
    path = "/api/siem-health/reports",
    tag = "siem_health",
    params(ListReportsParams),
    responses(
        (status = 200, description = "Paginated list of health report summaries", body = ListReportsResponse),
        (status = 403, description = "Insufficient permissions"),
    ),
    security(("api_key" = []))
)]
pub async fn list_reports(
    State(state): State<AppState>,
    Extension(auth): Extension<AuthContext>,
    Query(params): Query<ListReportsParams>,
) -> Result<Json<ListReportsResponse>, ApiError> {
    crate::middleware::ensure_permission(&auth, nanosiem_core::auth::permissions::SETTINGS_SYSTEM)?;

    let limit = params.limit.clamp(1, 100);
    let offset = params.offset.max(0);

    let repo = SiemHealthRepository::new(state.pool.clone());
    let (reports, total) = repo
        .list_summaries(limit, offset)
        .await
        .map_err(|e| ApiError::DatabaseError(e.to_string()))?;

    Ok(Json(ListReportsResponse {
        reports,
        total,
        limit,
        offset,
    }))
}

/// Get the most recent SIEM health report
///
/// Returns the latest full health report including metrics, recommendations,
/// and dimension details. Returns 404 if no reports exist yet.
///
/// Requires the `settings:system` permission; per-source telemetry inside the
/// report is filtered to the viewer's source scope (NAN-1801).
///
/// GET /api/siem-health/reports/latest
#[utoipa::path(
    get,
    path = "/api/siem-health/reports/latest",
    tag = "siem_health",
    responses(
        (status = 200, description = "The most recent health report", body = SiemHealthReport),
        (status = 403, description = "Insufficient permissions"),
        (status = 404, description = "No health reports exist yet"),
    ),
    security(("api_key" = []))
)]
pub async fn get_latest_report(
    State(state): State<AppState>,
    Extension(auth): Extension<AuthContext>,
) -> Result<Json<SiemHealthReport>, ApiError> {
    crate::middleware::ensure_permission(&auth, nanosiem_core::auth::permissions::SETTINGS_SYSTEM)?;

    let repo = SiemHealthRepository::new(state.pool.clone());
    let mut report = repo
        .get_latest()
        .await
        .map_err(|e| ApiError::DatabaseError(e.to_string()))?
        .ok_or_else(|| ApiError::NotFound("No health reports exist yet".to_string()))?;

    filter_report_for_viewer(&mut report, &auth.effective_source_deny_set());

    Ok(Json(report))
}

/// Get a specific SIEM health report by ID
///
/// Returns the full health report including metrics, recommendations,
/// and dimension details.
///
/// Requires the `settings:system` permission; per-source telemetry inside the
/// report is filtered to the viewer's source scope (NAN-1801).
///
/// GET /api/siem-health/reports/{id}
#[utoipa::path(
    get,
    path = "/api/siem-health/reports/{id}",
    tag = "siem_health",
    params(
        ("id" = Uuid, Path, description = "Report UUID"),
    ),
    responses(
        (status = 200, description = "The requested health report", body = SiemHealthReport),
        (status = 403, description = "Insufficient permissions"),
        (status = 404, description = "Report not found"),
    ),
    security(("api_key" = []))
)]
pub async fn get_report(
    State(state): State<AppState>,
    Extension(auth): Extension<AuthContext>,
    Path(id): Path<Uuid>,
) -> Result<Json<SiemHealthReport>, ApiError> {
    crate::middleware::ensure_permission(&auth, nanosiem_core::auth::permissions::SETTINGS_SYSTEM)?;

    let repo = SiemHealthRepository::new(state.pool.clone());
    let mut report = repo.get_by_id(id).await.map_err(|e| match e {
        nanosiem_core::siem_health::SiemHealthRepositoryError::NotFound(msg) => {
            ApiError::NotFound(msg)
        }
        other => ApiError::DatabaseError(other.to_string()),
    })?;

    filter_report_for_viewer(&mut report, &auth.effective_source_deny_set());

    Ok(Json(report))
}

/// Manually trigger a SIEM health check (admin only)
///
/// Runs the full health check pipeline: collect metrics from ClickHouse and PostgreSQL,
/// analyze with AI (or fallback scoring), and store the report. This is the same pipeline
/// that runs automatically every 12 hours.
///
/// Requires the `settings:system` permission.
///
/// POST /api/siem-health/reports/trigger
#[utoipa::path(
    post,
    path = "/api/siem-health/reports/trigger",
    tag = "siem_health",
    responses(
        (status = 200, description = "Health check triggered successfully", body = TriggerResponse),
        (status = 403, description = "Insufficient permissions"),
    ),
    security(("api_key" = []))
)]
pub async fn trigger_health_check(
    State(state): State<AppState>,
    Extension(auth): Extension<AuthContext>,
) -> Result<Json<TriggerResponse>, ApiError> {
    // Require admin permission
    crate::middleware::ensure_permission(&auth, nanosiem_core::auth::permissions::SETTINGS_SYSTEM)?;

    let repo = SiemHealthRepository::new(state.pool.clone());

    let ch_client = state.dual_pool().clickhouse().clone();
    let is_clustered = state.dual_pool().table_names().is_clustered();

    // Construct the SiemHealthAiAnalyzer for this trigger. Enterprise builds
    // wrap the live meloD AI client; open-core builds use the noop analyzer,
    // which returns `Unavailable` and lets the scheduler fall through to the
    // rules-based `analyzer::fallback_report`.
    use std::sync::Arc;
    use nanosiem_core::extensions::SiemHealthAiAnalyzer;
    #[cfg(not(feature = "enterprise"))]
    use nanosiem_core::extensions::NoopSiemHealthAiAnalyzer;

    #[cfg(feature = "enterprise")]
    let ai_analyzer: Arc<dyn SiemHealthAiAnalyzer> = {
        use nanosiem_core::extensions::{AiClient, NoopAiClient};
        let ai_client: Arc<dyn AiClient> = state
            .melod_service
            .read()
            .await
            .as_ref()
            .map(|s| s.ai_client_arc())
            .map(|shared| {
                Arc::new(nanosiem_enterprise::melod::MelodAiClientBridge::new(shared))
                    as Arc<dyn AiClient>
            })
            .unwrap_or_else(|| Arc::new(NoopAiClient));
        Arc::new(nanosiem_enterprise::siem_health::AiPoweredSiemHealthAnalyzer::new(ai_client))
    };
    #[cfg(not(feature = "enterprise"))]
    let ai_analyzer: Arc<dyn SiemHealthAiAnalyzer> = Arc::new(NoopSiemHealthAiAnalyzer);

    let report_id = nanosiem_core::siem_health::scheduler::run_health_check_with_trigger(
        &state.pool,
        &ch_client,
        is_clustered,
        ai_analyzer.as_ref(),
        &repo,
        Some(auth.user_id()),
    )
    .await;

    match report_id {
        Some(id) => Ok(Json(TriggerResponse {
            report_id: Some(id),
            message: "Health check completed successfully".to_string(),
        })),
        None => Err(ApiError::InternalError(
            "Health check failed to produce a report".to_string(),
        )),
    }
}

#[derive(utoipa::OpenApi)]
#[openapi(
    paths(list_reports, get_latest_report, get_report, trigger_health_check),
    components(schemas(
        ListReportsResponse,
        TriggerResponse,
        SiemHealthReport,
        SiemHealthReportSummary,
    ))
)]
pub struct SiemHealthApiDoc;
