// SPDX-License-Identifier: AGPL-3.0-or-later

//! Alert model

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

use super::Severity;
use crate::typeid;

/// Alert status
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, utoipa::ToSchema,
)]
#[sqlx(type_name = "text", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum AlertStatus {
    New,
    Acknowledged,
    Closed,
}

/// Alert disposition when closed
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, sqlx::Type, utoipa::ToSchema,
)]
#[sqlx(type_name = "text", rename_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum Disposition {
    TruePositive,
    FalsePositive,
    Benign,
}

/// An alert generated by a detection rule
#[derive(Debug, Clone, Serialize, Deserialize, FromRow, utoipa::ToSchema)]
pub struct Alert {
    #[serde(with = "typeid::alert")]
    #[schema(value_type = String)]
    pub id: Uuid,
    // NAN-1356: nullable — the FK `alerts_rule_id_fkey ... ON DELETE SET NULL`
    // sets this to NULL when the source detection rule is deleted. Decoding it as
    // a non-optional `Uuid` 500'd the entire `GET /api/alerts` list.
    #[serde(with = "typeid::rule::opt", default, skip_serializing_if = "Option::is_none")]
    #[schema(value_type = Option<String>)]
    pub rule_id: Option<Uuid>,
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rule_name: Option<String>,
    pub severity: Severity,
    pub status: AlertStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disposition: Option<Disposition>,
    pub matched_events: serde_json::Value,
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matched_event_count: Option<i32>,
    /// Hash of matched events for deduplication
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_hash: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub acknowledged_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub acknowledged_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    /// Latest triage verdict type
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub triage_verdict: Option<String>,
    /// Latest triage confidence score
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub triage_confidence: Option<f64>,
    /// Latest triage full verdict details
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub triage_verdict_details: Option<serde_json::Value>,
    /// Reference to the case this alert belongs to
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none", with = "typeid::case::opt")]
    #[schema(value_type = Option<String>)]
    pub case_id: Option<Uuid>,
    /// NAN-1541: alert-spine discriminator — what produced this alert.
    /// One of `detection`, `metric_monitor`, `slo`, `synthetic`. Defaults to
    /// `detection` for every pre-spine row (migration 212).
    #[sqlx(default)]
    #[serde(default = "default_alert_kind")]
    pub kind: String,
    /// NAN-1541: the producer's identifier as text — the detection rule UUID
    /// for `detection` alerts, or the monitor/check typeid for observability
    /// alerts. NULL for legacy rows whose rule was deleted.
    #[sqlx(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_id: Option<String>,
}

/// Default discriminator for alerts deserialized without an explicit `kind`
/// (legacy payloads). Mirrors the migration-212 column default.
fn default_alert_kind() -> String {
    "detection".to_string()
}

/// Input for creating a new alert
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct NewAlert {
    #[serde(with = "typeid::rule")]
    #[schema(value_type = String)]
    pub rule_id: Uuid,
    pub severity: Severity,
    pub matched_events: serde_json::Value,
    /// Optional event hash for deduplication
    #[serde(default)]
    pub event_hash: Option<String>,
}

/// Input for acknowledging an alert
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct AcknowledgeAlert {
    pub acknowledged_by: String,
}

/// Input for closing an alert
#[derive(Debug, Clone, Serialize, Deserialize, utoipa::ToSchema)]
pub struct CloseAlert {
    pub closed_by: String,
    pub disposition: Disposition,
}
