-- AI Failures table for tracking and debugging AI query generation issues
-- Stores failures from all AI agents (query, dashboard, detection, parser, summarize)

CREATE TABLE IF NOT EXISTS public.ai_failures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_type TEXT NOT NULL,
    user_request TEXT NOT NULL,
    generated_query TEXT NOT NULL,
    error_message TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    was_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for efficient querying by time (most recent first)
CREATE INDEX IF NOT EXISTS idx_ai_failures_created_at
ON public.ai_failures (created_at DESC);

-- Index for filtering by agent type
CREATE INDEX IF NOT EXISTS idx_ai_failures_agent_type
ON public.ai_failures (agent_type);

-- Index for finding unresolved failures
CREATE INDEX IF NOT EXISTS idx_ai_failures_unresolved
ON public.ai_failures (was_resolved, created_at DESC)
WHERE was_resolved = FALSE;

COMMENT ON TABLE public.ai_failures IS 'Tracks AI-generated query failures for debugging and analysis';
COMMENT ON COLUMN public.ai_failures.agent_type IS 'Type of AI agent: query, dashboard, detection, parser, summarize';
COMMENT ON COLUMN public.ai_failures.user_request IS 'Original natural language request from the user';
COMMENT ON COLUMN public.ai_failures.generated_query IS 'The query generated by the AI that failed';
COMMENT ON COLUMN public.ai_failures.error_message IS 'Error message from validation or execution';
COMMENT ON COLUMN public.ai_failures.retry_count IS 'Number of retry attempts made';
COMMENT ON COLUMN public.ai_failures.was_resolved IS 'Whether the failure was eventually resolved after retries';
