-- NAN-615: per-tenant suppression of /health findings
--
-- The AI on /health surfaces recommendations that are technically true but
-- contextually wrong for a given tenant (e.g. "windows_sysmon src_ip 7.7%" is
-- expected for that traffic mix). Without a way to mark a finding as "not an
-- issue", the same recommendation re-appears every report cycle and erodes
-- trust in the report.
--
-- A suppression is keyed by `finding_signature` — a deterministic hash
-- generated by the backend from the recommendation's normalized title +
-- extracted entities. Same class of finding hashes the same on consecutive
-- runs, so creating one suppression silences that class until it is undone.
--
-- The active suppressions are injected into the system prompt on every
-- subsequent /health run, so the AI explicitly omits those classes (with an
-- escape hatch when the underlying metric materially regresses).

CREATE TABLE IF NOT EXISTS siem_health_finding_suppressions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- Deterministic hash of the recommendation class. Generated by
    -- nanosiem-core's `finding_signature` module so re-runs produce stable IDs.
    finding_signature TEXT NOT NULL,
    -- Display title at suppression time, kept verbatim for the suppressed-list
    -- view and for the prompt's "previously suppressed" context block. The
    -- AI sees this verbatim, so do not normalize.
    title TEXT NOT NULL,
    -- User-supplied reason ("sysmon doesn't have src_ip on process events").
    -- Fed back into the prompt verbatim so the AI can judge whether the
    -- reasoning still applies.
    reason TEXT NOT NULL,
    created_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Soft delete via timestamp instead of bool — preserves "when undone" for
    -- the admin view and lets us re-activate cheaply if needed.
    deactivated_at TIMESTAMPTZ,
    deactivated_by UUID REFERENCES users(id)
);

-- Only one active suppression per signature. Re-suppressing a previously
-- undone finding inserts a new row.
CREATE UNIQUE INDEX idx_siem_health_finding_suppressions_active_signature
    ON siem_health_finding_suppressions (finding_signature)
    WHERE deactivated_at IS NULL;

-- Lookup all active suppressions for prompt injection.
CREATE INDEX idx_siem_health_finding_suppressions_active
    ON siem_health_finding_suppressions (created_at DESC)
    WHERE deactivated_at IS NULL;
